### PR TITLE
1.16.4 Update

### PR DESCRIPTION
**Pull request by rikka0w0**
After spending 3 hours on this => Update to 1.16.4, version => 2.5, fix some small bugs

### CODE REVIEW

**Comment by srnyx** [comment]
So I'm guessing this means the mod works on 1.16 versions higher than 1.16.1 now?

**Comment by Globox1997** [comment]
Haven't checked it but rikka0w0 did a great job :)

**Comment by srnyx** [comment]
> Haven't checked it but rikka0w0 did a great job :)

How do I download it?

**Comment by Globox1997** [comment]
you could compile it yourself or download it here [https://github.com/Globox1997/MobZ/issues/20#issuecomment-775119727](https://github.com/Globox1997/MobZ/issues/20#issuecomment-775119727)

**Comment by srnyx** [comment]
https://pastebin.com/TtXjyuu6

**Comment by Globox1997** [comment]
[https://www.curseforge.com/minecraft/mc-mods/mobz/files/3210857](https://www.curseforge.com/minecraft/mc-mods/mobz/files/3210857) uploaded it on cf
thank you @rikka0w0

**Comment by srnyx** [comment]
@rikka0w0 
My server is crashing with this 1.16.5 version: https://pastebin.com/TtXjyuu6

**Comment by Globox1997** [comment]
Looks like mod incompat due to a redirect in mobz

**Comment by srnyx** [comment]
> Looks like mod incompat due to a redirect in mobz

Yeah, but which mod?

**Comment by Globox1997** [comment]
another mod which adds shields

**Comment by srnyx** [comment]
> another mod which adds shields

Netherite Plus Mod and The Bumblezone both add a shield

**Comment by Globox1997** [comment]
[mobz-2.4.5.zip](https://github.com/Globox1997/MobZ/files/6016516/mobz-2.4.5.zip)
please unzip :)

**Pull request merged**
